### ISSUE TITLE
Cannot create new project or open existing image

### ISSUE THREAD

**Issue by UpcraftLP** [DeflatedPickle/Rawky#26]
creating a new file opens a width/height dialog, and does nothing after that.
similar for importing an existing image.

Rawky Version: 0.9.1-alpha

(this is after creating a new file):
![image](https://user-images.githubusercontent.com/10714589/69845841-56335d80-1272-11ea-8d1b-66a41635eaac.png)

EDIT: this only applies to the jar version, and I am getting the same issue on v0.7.6-alpha, too (didn't test others but assume it's the same there).

**Comment by DeflatedPickle** [comment]
Could you send part of the stacktrace (run the JAR from a terminal with `java -jar [path to jar]`)? I've never had these problems.

**Comment by UpcraftLP** [comment]
```
[main] INFO org.reflections.Reflections - Reflections took 67 ms to scan 1 urls, producing 5 keys and 21 values
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
        at bibliothek.gui.dock.common.intern.EfficientControlFactory.createController(EfficientControlFactory.java:49)
        at bibliothek.gui.dock.common.CControl.init(CControl.java:477)
        at bibliothek.gui.dock.common.CControl.<init>(CControl.java:455)
        at bibliothek.gui.dock.common.CControl.<init>(CControl.java:439)
        at bibliothek.gui.dock.common.CControl.<init>(CControl.java:384)
        at bibliothek.gui.dock.common.CControl.<init>(CControl.java:361)
        at com.deflatedpickle.rawky.MainKt$main$1.run(main.kt:56)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java
:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 2
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3720)
        at java.base/java.lang.String.substring(String.java:1909)
        at bibliothek.gui.DockUI.registerColors(DockUI.java:169)
        at bibliothek.gui.DockUI.<init>(DockUI.java:133)
        at bibliothek.gui.DockUI.getDefaultDockUI(DockUI.java:120)
        at bibliothek.gui.DockController.<clinit>(DockController.java:145)
        ... 20 more
[AWT-EventQueue-0] INFO org.reflections.Reflections - Reflections took 30 ms to scan 1 urls, producing 21 keys and 112 v
alues

```

**Comment by DeflatedPickle** [comment]
Oh, lovely. It's from a dependency, I can't even fix this. I'll report it to them after checking that line and maybe make a pull.
